// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef chpldbg_fl_h
#define chpldbg_fl_h
#include <FL/Fl.H>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <pthread.h>
#include <errno.h>
#include <cstdlib>
#include <unistd.h>
#include "CommInput.h"
#include "CommandLog.h"
#include "LocaleTab.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *MainWindow;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs;
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *disp;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menu;
int start_fltk_gui(int numTabs, int r_fd, int w_fd);
void make_tabs(int numTabs, Fl_Text_Buffer** tabBuffs);
void tabs_cb(Fl_Widget* w, void*);
int get_names(char** names, int size);
void * fltk_reader_thread(void *arg);
#endif
